name: CI Pipeline for Blackjack Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      DB_USER: root
      DB_PASSWORD: dbuserdbuser
      DB_HOST: localhost
      DB_NAME: blackjack

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.9

      # Step 3: Install Dependencies
      - name: Install Dependencies
        run: |
          pip install pytest pymysql

      # Step 4: Run Tests
      - name: Run Test Suite
        run: |
          pytest app/tests/test_app.py -v
